version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://${RAILWAY_PUBLIC_DOMAIN}/api}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL:-wss://${RAILWAY_PUBLIC_DOMAIN}/ws}
    depends_on:
      - backend
    networks:
      - inventory-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-change-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - API_V1_STR=${API_V1_STR:-/api/v1}
      - PROJECT_NAME=${PROJECT_NAME:-Inventory Management System}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-["https://${RAILWAY_PUBLIC_DOMAIN}"]}
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge 