[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "bash force_migrate.sh && bash start_railway.sh"

[env]
PYTHON_VERSION = "3.10" 