"""Add user roles and permissions

Revision ID: b8c47f5a2e23
Revises: 1ae83dadffbd
Create Date: 2025-07-28 19:55:38.060888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c47f5a2e23'
down_revision: Union[str, None] = '1ae83dadffbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('ADMIN', 'MANAGER', 'STAFF', 'VIEWER', name='userrole')
    userrole_enum.create(op.get_bind())
    
    # Add columns
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='STAFF'))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'department')
    op.drop_column('users', 'role')
    
    # Drop the enum type
    userrole_enum = sa.Enum(name='userrole')
    userrole_enum.drop(op.get_bind())
    # ### end Alembic commands ###
